language: php

sudo: false

dist: trusty

cache:
    directories:
        - $HOME/.composer/cache

install: composer install

matrix:
    include:
        -
            php: 7.1
        -
            php: nightly
    allow_failures:
        - php: nightly

script:
    - vendor/bin/phpunit
    - vendor/bin/phpspec run
